[XBOX]
# Buttons - NONE, LB, RB, LT, RT, LS, RS, UP, DOWN, LEFT, RIGHT, A, B, X, Y
# System Buttons - BACK, START
# Left Stick Directions - LS-UP, LS-DOWN, LS-LEFT, LS-RIGHT
# Right Stick Directions - RS-UP, RS-DOWN, RS-LEFT, RS-RIGHT
LB=LB
RB=

BACK=BACK
START=START

UP=UP
LEFT=LEFT
RIGHT=RIGHT
DOWN=DOWN


Y=Y
X=X
A=A
B=B
B_KB=SPACE 

LS=LS
RS=RS
513753513751371
[SETTINGS]
SWAP-STICKS=0
SWAP-TRIGGERS=0

[MOTION]
# Buttons for wheel buttons activation - L1, R1, L2, R2,  UP, DOWN, LEFT, RIGHT, L3, R3
# Sony - CROSS, CIRCLE, SQUARE, TRIANGLE, SHARE, OPTIONS
# DualSense Edge - L4, R4
# Nintendo controllers - ZL, ZR, B, A, Y, X, MINUS, PLUS, SL, SR
WHEEL-ACTIVATION=R1

# Xbox buttons
WHEEL-DEFAULT=NONE

WHEEL-UP=NONE

WHEEL-LEFT=NONE

WHEEL-RIGHT=NONE

WHEEL-DOWN=NONE


WHEEL-DEFAULT=0
WHEEL-UP_KB=3
WHEEL-UP-LEFT_KB=2
WHEEL-LEFT_KB=1
WHEEL-UP-RIGHT_KB=4
WHEEL-RIGHT_KB=5
WHEEL-DOWN_KB=7
WHEEL-DOWN-LEFT_KB=8
WHEEL-DOWN-RIGHT_KB=6


[JOYCONS]
SL=B
SR=X
# HOME=Y
# HOME_KB=SPACE
# CAPTURE=DOWN
# CAPTURE_KB=SPACE

[DUALSENSE-EDGE]
L4=B
R4=X